<?php

namespace SDtools\ClassLoader;

require_once dirname(__FILE__) . '/../../../../src/SDtools/ClassLoader/SplClassLoader.php';

/**
 * Test class for SplClassLoader.
 * Generated by PHPUnit on 2012-02-28 at 21:57:25.
 */
class SplClassLoaderTest extends \PHPUnit_Framework_TestCase {
    
    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testAddNamespace().
     */
    public function testAddNamespace() {
        $Lib_path =  realpath(__DIR__.'/../../../');
        SplClassLoader::addNamespace(array('Lib' => $Lib_path));
        $foo = new \Lib\Foo();
        ok( $foo );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testAddPrefix().
     */
    public function testAddPrefix() {
        $Lib_path =  realpath(__DIR__.'/../../../');
        SplClassLoader::addPrefix(array('Lib' => $Lib_path));
        $apple = new \Lib_apple();
        ok( $apple );
    }
    
}

?>
